ENCODER_ENABLE = yes
OLED_ENABLE = no
OLED_DRIVER = SSD1306
VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes        # Enable keyboard RGB underglow


SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
COMMAND_ENABLE = no
MAGIC_ENABLE = no
CONSOLE_ENABLE = no
MUSIC_ENABLE = no

TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
